# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install necessary packages
#RUN pip install --no-cache-dir -r requirements_llama.txt

# Run the Llama model server
CMD ["python", "app/llama_server.py"]
