version: '3.8'

services:
  web:
    image: flask_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+asyncpg://postgres:rootuser@db:5432/book_db
    depends_on:
      - db
      - llama

  llama:
    image: llama3:latest
    build:
      context: .
      dockerfile: Dockerfile.llama
    command: python app/llama_server.py
    ports:
      - "5000:5000"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootuer
      POSTGRES_DB: book_db
    ports:
      - "5432:5432"
